content_articles_homepage:
    path:     /
    defaults: { _controller: ContentArticleBundle:Article:index, name:Quinn }
    
content_articles_display:
    path:     /article/display/{articleId}
    defaults: { _controller: ContentArticleBundle:Article:display }
    
content_articles_create:
    path:     /article/create
    defaults: { _controller: ContentArticleBundle:Article:create }

content_articles_edit:
    path:     /article/edit/{id}
    defaults: { _controller: ContentArticleBundle:Article:edit }
    requirements:
        title: "[a-zA-Z]+"
           
content_articles_tag:
    path:    /article/tag/{tag}
    defaults: { _controller: ContentArticleBundle:Article:tag }
content_articles_search:
    path:    /article/search
    defaults: { _controller: ContentArticleBundle:Article:search }
