fundamental_common_homepage:
    path:     /
    defaults: { _controller: FundamentalCommonBundle:CommonView:index ,name: guest}

fundamental_common_navbar:
    path:     /common/nav
    defaults: { _controller: FundamentalCommonBundle:CommonView:nav }
    
funcamental_common_header:
    path:     /common/header
    defaults: { _controller: FundamentalCommonBundle:CommonView:header }